FROM elasticsearch:7.16.2

WORKDIR /usr/share/elasticsearch/

RUN bin/elasticsearch-plugin install https://github.com/netcrazy/elasticsearch-jaso-analyzer/releases/download/v7.16.2/jaso-analyzer-plugin-7.16.2-plugin.zip
